server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: "create"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  datasource:
    url: "jdbc:${CUSTOM_DB_URL}?user=${CUSTOM_DB_USER}&password=${CUSTOM_DB_PASSWORD}&verifyServerCertificate=false&useSSL=false&requireSSL=false"
    driver-class-name: "com.mysql.jdbc.Driver"
