server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: "create"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  datasource:
    url: "jdbc:${DATASOURCE_URL}"
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: "com.mysql.jdbc.Driver"
